### ISSUE TITLE
Generate HTML documentation on pipeline

### ISSUE THREAD

**Issue by debemdeboas** [debemdeboas/virtual-machine#9]
Add documentation generation with `pydoc` on merge.

**Comment by debemdeboas** [comment]
[Doc](https://github.com/marketplace/actions/generate-documentation)

**Comment by debemdeboas** [comment]
Maybe this will do?

```yml
name: Generate Documentation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Github Action genshdoc
      id: action-genshdoc
      uses: vargiuscuola/genshdoc@master
    - name: genshdoc result
      run: echo "The result of genshdoc Action was ${{ steps.action-genshdoc.outputs.result }}"
    - name: Commit files
      run: |
        echo ${{ github.ref }}
        git add .
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m ":green_heart: Automated documentation" -a | exit 0
    - name: Push changes
      if: github.ref == 'refs/heads/master'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
```
